stages:
  - test
  - package

variables:
    DOCKER_IMAGE_CORE_EMBEDDED: "docker-registry.linagora.com:5000/linshare-snapshots/linshare-core-embedded-for-tests"
    DOCKER_IMAGE_CORE_TEST: "docker-registry.linagora.com:5000/linshare-snapshots/linshare-core-test"
    GIT_DEPTH: "1"

.build-docker-tpl: &build-docker-tpl
  image: docker-registry.linagora.com:5000/linshare-snapshots/linshare-dind:latest
  tags:
    - docker
  services:
      - name: docker-registry.linagora.com:5000/linshare-snapshots/linshare-dind:latest
        alias: docker-dind

check_author:
  image: docker-registry.linagora.com:5000/lgs-releases/gitlab-integrity-checks:latest
  stage: test
  tags:
    - ultralight
  script:
    - check_author.py check "$GITLAB_USER_EMAIL" "$GITLAB_USER_NAME" --no-accents
  except:
    refs:
      - tags@linagora/lgs/linshare/products/linshare-core-tests
      - /^release-.*/@linagora/lgs/linshare/products/linshare-core-tests

pylint:
  stage: test
  tags:
    - docker
  image: docker-registry.linagora.com:5000/linshare-snapshots/python:3.9-slim-buster
  allow_failure: true
  script:
    - pip install pylint pytest
    - pip install -r requirements.txt
    - pylint --disable=R0801 linshare_core_tests/

flake:
  stage: test
  tags:
    - docker
  image: docker-registry.linagora.com:5000/linshare-snapshots/python:3.9-slim-buster
  script:
    - pip install flake8
    - pip install -r requirements.txt
    - flake8 linshare_core_tests/

pylint_badge:
  stage: test
  image: docker-registry.linagora.com:5000/linshare-snapshots/python:3.9-slim-buster
  tags:
    - docker
  before_script:
    - mkdir -p badges pylint-report
    - echo undefined > badges/$CI_JOB_NAME.score
    - pip install pylint-gitlab
  script:
    - pylint --disable=R0801 --exit-zero --output-format=text $(find ./linshare_core_tests/ -type f -name "*.py") | tee /tmp/pylint.txt
    - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > badges/$CI_JOB_NAME.score
    - pylint --disable=R0801 --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter $(find ./linshare_core_tests/ -type f -name "*.py") > codeclimate.json
    - pylint --disable=R0801 --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter $(find ./linshare_core_tests/ -type f -name "*.py") > pylint-report/index.html
  after_script:
    - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat badges/$CI_JOB_NAME.score) --file=badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
    - |
      echo "Your score is: $(cat badges/$CI_JOB_NAME.score)"
  artifacts:
    paths:
      - badges
      - pylint-report
    reports:
      codequality: codeclimate.json
    when: always

see-reports:
  stage: package
  image: alpine:latest
  tags:
    - docker
  script:
    - "echo Once pyling job is complete, you will be able to see the result here: https://ci.linagora.com/linagora/lgs/linshare/products/linshare-core-tests/-/jobs/artifacts/${CI_COMMIT_REF_NAME}/browse?job=pylint"
 

test-api-branch-core-master:
  stage: test
  tags:
    - docker
  image: docker-registry.linagora.com:5000/linshare-snapshots/python:3.9-slim-buster
  services:
    - name: "${DOCKER_IMAGE_CORE_EMBEDDED}:master"
      alias: linshare
    - name: docker-registry.linagora.com:5000/linshare-releases/linshare-ldap-for-tests:2.0
      alias: ldap
  variables:
    CONFIG_FILE_ADMIN: linshare.admin.test.ini
    CONFIG_FILE_USER: linshare.user.test.ini
    LS_TEST_DEBUG: 0
  script:
    - pip install -r requirements.txt
    - ./patch_gitlab.py
    - ./tests_linshare.py
  only:
    refs:
      - master@linagora/lgs/linshare/products/linshare-core-tests

test-api-branch-maintenance-x-legacy:
  stage: test
  tags:
    - docker
  image: docker-registry.linagora.com:5000/linshare-snapshots/python:3.9-slim-buster
  services:
    - name: "${DOCKER_IMAGE_CORE_EMBEDDED}:${CI_COMMIT_REF_SLUG}"
      alias: linshare
    - name: docker-registry.linagora.com:5000/linshare-releases/linshare-ldap-for-tests:2.0
      alias: ldap
  variables:
    CONFIG_FILE_ADMIN: linshare.admin.test.ini
    CONFIG_FILE_USER: linshare.user.test.ini
    LS_TEST_DEBUG: 0
  script:
    - pip install -r requirements.txt
    - ./patch_gitlab.py
    - ./tests_linshare.py
  only:
    refs:
      - /^maintenance-.*/@linagora/lgs/linshare/products/linshare-core-tests

test-api-branch-maintenance-x:
  stage: test
  tags:
    - docker
  image: docker-registry.linagora.com:5000/linshare-snapshots/python:3.9-slim-buster
  services:
    - name: "${DOCKER_IMAGE_CORE_EMBEDDED}:${CI_COMMIT_REF_SLUG}"
      alias: linshare
    - name: docker-registry.linagora.com:5000/linshare-releases/linshare-ldap-for-tests:2.0
      alias: ldap
  variables:
    CONFIG_FILE_ADMIN: linshare.admin.test.ini
    CONFIG_FILE_USER: linshare.user.test.ini
  script:
    - pip install -r requirements.txt
    - ./patch_gitlab.py
    - tox
  artifacts:
    when: always
    reports:
      junit: report.xml
  only:
    refs:
      - /^maintenance-.*/@linagora/lgs/linshare/products/linshare-core-tests

test-api-branch-core-master-legacy:
  stage: test
  tags:
    - docker
  image: docker-registry.linagora.com:5000/linshare-snapshots/python:3.9-slim-buster
  services:
    - name: "${DOCKER_IMAGE_CORE_EMBEDDED}:master"
      alias: linshare
    - name: docker-registry.linagora.com:5000/linshare-releases/linshare-ldap-for-tests:2.0
      alias: ldap
  variables:
    CONFIG_FILE_ADMIN: linshare.admin.test.ini
    CONFIG_FILE_USER: linshare.user.test.ini
    LS_TEST_DEBUG: 0
  script:
    -  pip install -r requirements.txt
    - ./patch_gitlab.py
    - ./tests_linshare.py
  except:
    refs:
      - master@linagora/lgs/linshare/products/linshare-core-tests
      - tags@linagora/lgs/linshare/products/linshare-core-tests

test-api-branch-core-master:
  stage: test
  tags:
    - docker
  image: docker-registry.linagora.com:5000/linshare-snapshots/python:3.9-slim-buster
  services:
    - name: "${DOCKER_IMAGE_CORE_EMBEDDED}:master"
      alias: linshare
    - name: docker-registry.linagora.com:5000/linshare-releases/linshare-ldap-for-tests:2.0
      alias: ldap
  variables:
    CONFIG_FILE_ADMIN: linshare.admin.test.ini
    CONFIG_FILE_USER: linshare.user.test.ini
  script:
    -  pip install -r requirements.txt
    - ./patch_gitlab.py
    - tox
  artifacts:
    when: always
    reports:
      junit: report.xml
  except:
    refs:
      - master@linagora/lgs/linshare/products/linshare-core-tests
      - tags@linagora/lgs/linshare/products/linshare-core-tests

test-api-same-core-branch-legacy:
  stage: test
  allow_failure: true
  tags:
    - docker
  image: docker-registry.linagora.com:5000/linshare-snapshots/python:3.9-slim-buster
  services:
    - name: "${DOCKER_IMAGE_CORE_EMBEDDED}:${CI_COMMIT_REF_SLUG}"
      alias: linshare
    - name: docker-registry.linagora.com:5000/linshare-releases/linshare-ldap-for-tests:2.0
      alias: ldap
  variables:
    CONFIG_FILE_ADMIN: linshare.admin.test.ini
    CONFIG_FILE_USER: linshare.user.test.ini
    LS_TEST_DEBUG: 0
  script:
    -  pip install -r requirements.txt
    - ./patch_gitlab.py
    - ./tests_linshare.py
  except:
    refs:
      - /^maintenance-.*/@linagora/lgs/linshare/products/linshare-core-tests
      - master@linagora/lgs/linshare/products/linshare-core-tests
      - tags@linagora/lgs/linshare/products/linshare-core-tests

test-api-same-core-branch:
  stage: test
  allow_failure: true
  tags:
    - docker
  image: docker-registry.linagora.com:5000/linshare-snapshots/python:3.9-slim-buster
  services:
    - name: "${DOCKER_IMAGE_CORE_EMBEDDED}:${CI_COMMIT_REF_SLUG}"
      alias: linshare
    - name: docker-registry.linagora.com:5000/linshare-releases/linshare-ldap-for-tests:2.0
      alias: ldap
  variables:
    CONFIG_FILE_ADMIN: linshare.admin.test.ini
    CONFIG_FILE_USER: linshare.user.test.ini
  script:
    -  pip install -r requirements.txt
    - ./patch_gitlab.py
    - tox
  artifacts:
    when: always
    reports:
      junit: report.xml
  except:
    refs:
      - /^maintenance-.*/@linagora/lgs/linshare/products/linshare-core-tests
      - master@linagora/lgs/linshare/products/linshare-core-tests
      - tags@linagora/lgs/linshare/products/linshare-core-tests

build:
  <<: *build-docker-tpl
  stage: package
  tags:
    - docker
  variables:
    DOCKER_HOST: "tcp://docker-dind"
  script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}" docker-registry.linagora.com:5000
    - docker build . -t "${DOCKER_IMAGE_CORE_TEST}:${CI_COMMIT_REF_SLUG}"
    - docker push "${DOCKER_IMAGE_CORE_TEST}:${CI_COMMIT_REF_SLUG}"
    - docker logout docker-registry.linagora.com:5000

