# vim: syntax=yaml textwidth=120 expandtab tabstop=2 softtabstop=2 shiftwidth=2 autoindent

# Docker compose file for a full-featured Linshare architecture
version: '3.7'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.101.0.0/16

services:

  backend:
    image: docker-registry.linagora.com:5000/linshare-snapshots/linshare-core-embedded-for-tests:${LS_BACKEND_BRANCH:-master}
    container_name: linshare_backend_test
    ports:
      - 8080:8080
   #volumes:
   #   - ./conf/backend/log4j.properties:/etc/linshare/log4j.properties
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:8080/linshare/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ldap:
    container_name: linshare_ldap_test
    image: docker-registry.linagora.com:5000/linshare-releases/linshare-ldap-for-tests:2.0
    environment:
      - BITNAMI_DEBUG=false
    ports:
      - 2389:1389
      - 2636:1636
